# Operaciones de una matriz cuadrada
Utilizando un cuaderno de Jupyter Notebook y el lenguaje de programación Python, se realizaron las siguientes operaciones: 
- Una matriz cuadrada de 4x4. 
- Cálculo su inversa y su traspuesta. 
- Multiplicación de la matriz por un escalar. 
- El producto interno con una nueva matriz de dimensiones 4x2.


## Matriz cuadrada de 4x4

In [2]:
import numpy as np

# Crear una matriz cuadrada de 4x4
matriz_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])

print("Matriz 4x4:")
print(matriz_4x4)

Matriz 4x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Cálculo de la inversa y la traspuesta

In [5]:
# Cálculo de la inversa de la matriz
determinante = np.linalg.det(matriz_4x4)
print(f"Determinante de la matriz: {determinante}")

# Verificar si la matriz es invertible usando tolerancia
if abs(determinante) > 1e-10:
    # La matriz es invertible
    inversa_matriz = np.linalg.inv(matriz_4x4)
    print("\nInversa de la matriz 4x4:")
    print(inversa_matriz)
else:
    print("\nLa matriz no es invertible, generando una nueva matriz...")
    np.random.seed(45)
    matriz_4x4 = np.random.randint(1, 10, size=(4, 4))
    print("Nueva matriz 4x4:")
    print(matriz_4x4)
    # Verificar nuevamente si la nueva matriz es invertible
    determinante_nuevo = np.linalg.det(matriz_4x4)
    print(f"Determinante de la nueva matriz: {determinante_nuevo}")
    if abs(determinante_nuevo) > 1e-10:
        inversa_matriz = np.linalg.inv(matriz_4x4)
        print("\nInversa de la nueva matriz 4x4:")
        print(inversa_matriz)
    else:
        print("La nueva matriz tampoco es invertible.")

# Cálculo de la traspuesta de la matriz
traspuesta_matriz = matriz_4x4.T
print("\nTraspuesta de la matriz 4x4:")
print(traspuesta_matriz)


Determinante de la matriz: -378.99999999999966

Inversa de la matriz 4x4:
[[ 0.59366755  0.57255937 -0.65963061  0.06332454]
 [-0.40897098 -0.1055409   0.23218997  0.08970976]
 [-0.30870712 -0.33773087  0.34300792  0.08707124]
 [ 0.22163588 -0.03957784  0.08707124 -0.21635884]]

Traspuesta de la matriz 4x4:
[[4 5 7 6]
 [1 9 9 3]
 [6 2 8 9]
 [4 6 9 2]]


## Multiplicación de la matriz por un escalar

In [6]:
escalar = 7
matriz_escalar = matriz_4x4 * escalar

print(f"\nMatriz 4x4 multiplicada por el escalar {escalar}:")
print(matriz_escalar)


Matriz 4x4 multiplicada por el escalar 7:
[[28  7 42 28]
 [35 63 14 42]
 [49 63 56 63]
 [42 21 63 14]]


## Producto interno con una nueva matriz de dimensiones 4x2

In [7]:
matriz_4x2 = np.array([[1, 2],
                       [3, 4],
                       [5, 6],
                       [7, 8]])

print("\nMatriz 4x2:")
print(matriz_4x2)

producto_interno = np.dot(matriz_4x4, matriz_4x2)

print("\nProducto interno entre la matriz 4x4 y la matriz 4x2:")
print(producto_interno)


Matriz 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Producto interno entre la matriz 4x4 y la matriz 4x2:
[[ 65  80]
 [ 84 106]
 [137 170]
 [ 74  94]]
